name: afmo
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.7.0
  - seaborn>=0.13.0
  - python=3.11
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.2.2
  - statsmodels=0.14.2
  - pmdarima=2.0.4
  - pip
  - pip:
      - typer==0.12.3
      - streamlit==1.38.0
      - plotly==5.23.0

  - kaleido>=0.2.1
